development:
  dialect: postgres
  datasource: host=localhost port=5433 user=postgres password=p.123456 dbname=goproject_db sslmode=disable
  dir: internal/repository/postgres/migrations
  
docker:
  dialect: postgres
  datasource: host=localhost port=5435 user=postgres password=p.123456 dbname=goproject_db sslmode=disable
  dir: internal/repository/postgres/migrations