development:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=${DB_SSLMODE}
  dir: internal/repository/postgres/migrations