services:
  postgres:
    image: postgres:16
    container_name: postgres_full
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_full:/var/lib/postgresql/data

  redis:
      image: redis:7-alpine
      container_name: redis_full
      restart: always
      env_file:
        - .env
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
      volumes:
        - redis_data_full:/data

  api:
    build: .
    container_name: gin_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./config.yml:/app/config.yml
      - ./dbconfig.yml:/app/dbconfig.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./internal/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data_full:
  redis_data_full:
  grafana_data: