services:
  postgres:
    image: postgres:16
    container_name: postgres_full
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_full:/var/lib/postgresql/data

  api:
    build: .
    container_name: gin_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./config.yml:/app/config.yml
      - ./dbconfig.yml:/app/dbconfig.yml

volumes:
  postgres_data_full: